name: BuildForMac

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Unzip libraries
        run: unzip macOS/lib.zip

      - name: Build
        run: xcodebuild -project macOS/OpenSiv3D-GUIKit.xcodeproj/
