name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Extract libraries
        run: Expand-Archive -Path Dependencies\lib\Windows.zip -DestinationPath Dependencies\lib\

      - name: Build
        run: msbuild "Windows/OpenSiv3D GUIKit.vcxproj" /p:Platform=x64

  macOS:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract libraries
        run: unzip macOS/lib.zip

      - name: Build
        run: xcodebuild -project macOS/OpenSiv3D-GUIKit.xcodeproj/