name: CI

on:
  push:
    branches:
    - master
    - develop
    - devenv/fix-test-sources
  pull_request:
    branches:
    - master
    - develop

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Extract libraries
        run: |
          Expand-Archive -Path "Dependencies\lib\Windows\Siv3D.zip" -DestinationPath "Dependencies\lib\Windows\" -force
          Expand-Archive -Path "Dependencies\lib\Windows\ThirdParty.zip" -DestinationPath "Dependencies\lib\Windows\" -force

      - name: Build
        run: msbuild "Windows\OpenSiv3D GUIKit.vcxproj" /p:Platform=x64

      - name: Run Test
        run: msbuild "Windows\OpenSiv3D GUIKit Test.vcxproj" /p:Platform=x64

  macOS:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract libraries
        run: unzip -n Dependencies/lib/macOS.zip -d Dependencies/lib/

      - name: Build
        run: xcodebuild -project macOS/OpenSiv3D-GUIKit.xcodeproj/

      - name: Run Test
        run: xcodebuild -project macOS/OpenSiv3D-GUIKit-Test.xcodeproj/

  Linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: |
          cd Linux/
          mkdir build
          cd build/
          cmake ../

      - name: Build
        run: |
          cd Linux/build/
          make

      - name: Install packeages for OpenSiv3D
        run: |
          sudo apt install ninja-build
          sudo apt install libasound2-dev
          sudo apt install libavcodec-dev
          sudo apt install libavformat-dev
          sudo apt install libavutil-dev
          sudo apt install libboost-all-dev
          sudo apt install libcurl4-openssl-dev
          sudo apt install libgtk-3-dev
          sudo apt install libgif-dev
          sudo apt install libglu1-mesa-dev
          sudo apt install libharfbuzz-dev
          sudo apt install libmpg123-dev
          sudo apt install libopencv-dev
          sudo apt install libopus-dev
          sudo apt install libopusfile-dev
          sudo apt install libsoundtouch-dev
          sudo apt install libswresample-dev
          sudo apt install libtiff-dev
          sudo apt install libturbojpeg0-dev
          sudo apt install libudev-dev
          sudo apt install libvorbis-dev
          sudo apt install libwebp-dev
          sudo apt install libxft-dev
          sudo apt install uuid-dev
          sudo apt install xorg-dev
          sudo apt install libopenal-dev

      - name: Build OpenSiv3D
        run: |
          cd Linux/Test/
          git clone https://github.com/Siv3D/OpenSiv3D.git
          cd OpenSiv3D/
          mkdir Linux/build
          cd Linux/build/
          cmake -DCMAKE_BUILD_TYPE=Release -GNinja ..
          ninja

      - name: Build Test
        run: |
          cd Linux/Test/
          mkdir build
          cd build/
          cmake ../
          make