name: CI

on:
  push:
    branches:
    - master
    - develop
    - feature/platform-linux
  pull_request:
    branches:
    - master
    - develop

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Extract libraries
        run: |
          Expand-Archive -Path "Dependencies\lib\Windows\Siv3D.zip" -DestinationPath "Dependencies\lib\Windows\" -force
          Expand-Archive -Path "Dependencies\lib\Windows\ThirdParty.zip" -DestinationPath "Dependencies\lib\Windows\" -force

      - name: Build
        run: msbuild "Windows\OpenSiv3D GUIKit.vcxproj" /p:Platform=x64

      - name: Run Test
        run: msbuild "Windows\OpenSiv3D GUIKit Test.vcxproj" /p:Platform=x64

  macOS:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract libraries
        run: unzip -n Dependencies/lib/macOS.zip -d Dependencies/lib/

      - name: Build
        run: xcodebuild -project macOS/OpenSiv3D-GUIKit.xcodeproj/

      - name: Run Test
        run: xcodebuild -project macOS/OpenSiv3D-GUIKit-Test.xcodeproj/

  Linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Configure
        working-directory: Linux
        run: |
          mkdir build
          cd build
          make ../

      - name: Build
        working-directory: Linux/build
        run: make